#region Globals
global using System.Configuration;
global using  mono_financialbot_backend_cs_external_serivces.Providers.RabbitMQ.Interfaces;
global using mono_financialbot_backend_cs_external_serivces.Providers.RabbitMQ.Services;
global using mono_financialbot_backend_cs_external_serivces.Providers.RabbitMQ.Models;
global using mono_financialbot_backend_cs_external_serivces.Providers.Bot;
global using  mono_financialbot_backend_cs_external_serivces_integration.Providers.Stocks.Service;
#endregion